### ISSUE TITLE
ImportError when running flask run on finesse-backend

### ISSUE THREAD

**Issue by HsKocTets** [ai-cfia/ailab-db#70]
When attempting to launch the application with flask run in the finesse-backend repository, an ImportError related to the `psycopg` library is triggered. It is important to note that the `finesse-backend` repository does not directly use `psycopg`, but it imports the GitHub repository ailab-db, which does make use of this library.
### How to reproduce the problem:
1. Clone the finesse-backend repository.
1. Set up the repository by following the `INSTALLATION.md` protocol.
1. Run `flask run` in the terminal.
### Tasks:
- [ ] Analyze the ailab-db repository to identify what's causing the problem.
- [ ] Implement a solution in the ailab-db repository to avoid the necessity for finesse-backend to download `psycopg`.
- [ ] Test the implemented solution by reproducing the problem in `inesse-backend after making the necessary adjustments.
### Acceptance Criteria:
- Dependencies of ailab-db repository is reviewed.
- The implemented solution is tested, and finesse-backend successfully runs without the psycopg-related ImportError.

**Comment by rngadam** [comment]
@HsKocTets what is the error? what is the error log?

at which step is pip install'ed of the dependencies?

**Comment by ibrahim-kabir** [comment]
@rngadam I updated the issue with the error log containing the error.

**Comment by rngadam** [comment]
1) I see your error log is on Windows. We have not developed on Windows so far. I suggest you switch to using github codespaces (visual studio code in the cloud).
2) ```ImportError: no pq wrapper available.``` you are missing postgresql client libraries in your environment. You have to figure out how to install the dependency on your OS, but as an example your can look at how postgresql-client is installed in the Dockerfile: https://github.com/ai-cfia/ailab-db/blob/main/Dockerfile
