### ISSUE TITLE
QnA Documents Diverge from Azure Index Document Source

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/ailab-db#72]
## Summary:
The current QnA generation process relies on different documents than the Azure Indexes. QnAs are generated from the 'crawl' table, but Finesse use finesse-public-guidance index is generated from the 'public-guidance' blob storage. This causes issues with generating scores of 0 in the Finesse Benchmark tool located in the repository [finesse-backend](https://github.com/ai-cfia/finesse-backend). The script needs modification to generate documents from the blob storage instead of the 'louis_crawl' postgreSQL databse.

## Tasks:
- [ ] Modify the script to generate QnAs from the Index blob storage
- [ ] Test the new QnAs with the Finesse Benchmark tool
- [ ] Update [finesse-data](https://github.com/ai-cfia/finesse-data) with the new QnAs

## Acceptance Criteria:
- The script successfully connects to the Azure Blob Storage account.
- Documents are retrieved from the 'public-guidance' container in the Azure Blob Storage.
- QnAs are generated using documents from the blob storage.
- Running the Finesse Benchmark tool with the modified script does not result in scores of 0.

**Comment by rngadam** [comment]
AFAIK @k-allagbe imported guidance documents from the same crawl table into the blob storage?

**Comment by ibrahim-kabir** [comment]
> AFAIK [@k-allagbe](https://github.com/k-allagbe) imported guidance documents from the same crawl table into the blob storage?

@k-allagbe confirmed me they were imported from the crawl table. I will close this issue if you don't see any issues.
