### ISSUE TITLE
Add a Guidance Score

### ISSUE THREAD

**Issue by JolanThomassin** [ai-cfia/ailab-db#85]
# Enhancing Search Scores

In our [score weights](https://github.com/ai-cfia/ailab-db/blob/main/search-scores-and-weights.md), we have different scores, but two are missing: the Didactic score and the Guidance score. While the Didactic score was tested and proven to be irrelevant, the Guidance score has the potential to be very useful.

## Tasks

- [ ] Clone the current Schema.
- [ ] Determine how to identify a guidance page.
- [ ] Assign a score of 1 if it's a guidance page and 0 if it's not for every page.

**Comment by rngadam** [comment]
This is related to both Finesse and functionally database so has to be in both projects.
