### ISSUE TITLE
Refactor `ailab-db`: fix deprecations, smells and apply our good practices

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-db#92]
## Description
Refactor `ailab-db` to fix deprecated code, address smells and complexities, ensure good exception handling, and follow our best practices.

## Tasks
- [ ] Update deprecated code.
- [ ] Address code smells.
- [ ] Simplify complex code.
- [ ] Implement robust exception handling.
- [ ] Restructure using [our best practices](https://github.com/ai-cfia/dev-rel-docs).

## Acceptance Criteria
- All tests pass
- Our standards of code are met
- The team is satisfied
